version: '3.7'

services:
  # Backend Service
  backend:
    build:
      context: ./backend
    depends_on:
      - redis
    networks:
      - backend_network
    deploy:
      replicas: 10  # Scale backend to 10 instances (requires Docker Swarm)

  # Redis Service
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - backend_network

  # Frontend Service
  frontend:
    build:
      context: ./novacdn-frontend
    depends_on:
      - backend
    networks:
      - backend_network
    deploy:
      replicas: 10  # Scale frontend to 10 instances (requires Docker Swarm)
    # ⚠️ Remove ports mapping to avoid conflicts when scaling
    # Access through Nginx

  # Nginx Reverse Proxy
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"  # Expose app through Nginx
    depends_on:
      - frontend
      - backend
    networks:
      - backend_network

  # Edge Nodes (Simulated CDN)
  node1:
    build:
      context: ./novacdn-nodes/node1
    networks:
      - backend_network
      - edge_network

  node2:
    build:
      context: ./novacdn-nodes/node2
    networks:
      - backend_network
      - edge_network

  node3:
    build:
      context: ./novacdn-nodes/node3
    networks:
      - backend_network
      - edge_network

  node4:
    build:
      context: ./novacdn-nodes/node4
    networks:
      - backend_network
      - edge_network

  node5:
    build:
      context: ./novacdn-nodes/node5
    networks:
      - backend_network
      - edge_network

  node6:
    build:
      context: ./novacdn-nodes/node6
    networks:
      - backend_network
      - edge_network

  node7:
    build:
      context: ./novacdn-nodes/node7
    networks:
      - backend_network
      - edge_network

  node8:
    build:
      context: ./novacdn-nodes/node8
    networks:
      - backend_network
      - edge_network

  node9:
    build:
      context: ./novacdn-nodes/node9
    networks:
      - backend_network
      - edge_network

  node10:
    build:
      context: ./novacdn-nodes/node10
    networks:
      - backend_network
      - edge_network

networks:
  backend_network:
    driver: bridge
  edge_network:
    driver: bridge
