apiVersion: apps/v1
kind: Deployment
metadata:
  name: novacdn-frontend
spec:
  replicas: 2  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: novacdn-frontend
  template:
    metadata:
      labels:
        app: novacdn-frontend
    spec:
      containers:
        - name: frontend
          image: novacdn-frontend:latest  # Replace with your frontend image
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: novacdn-frontend
spec:
  selector:
    app: novacdn-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
