apiVersion: v1
kind: Service
metadata:
  name: novacdn-frontend
spec:
  selector:
    app: novacdn-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
