apiVersion: v1
kind: Service
metadata:
  name: novacdn-nginx
spec:
  selector:
    app: novacdn-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # You can also use NodePort for testing
