apiVersion: apps/v1
kind: Deployment
metadata:
  name: novacdn-redis
spec:
  replicas: 1  # Redis typically runs as a single instance in this case
  selector:
    matchLabels:
      app: novacdn-redis
  template:
    metadata:
      labels:
        app: novacdn-redis
    spec:
      containers:
        - name: redis
          image: engrtanimawo244/novacdn-redis:latest  # Updated to use the public Docker image
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: novacdn-redis
spec:
  selector:
    app: novacdn-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
