apiVersion: v1
kind: Service
metadata:
  name: novacdn-redis
spec:
  selector:
    app: novacdn-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
